### ISSUE TITLE
Cannot destructure property 'element' of 'children[i]' as it is undefined.

### ISSUE THREAD

**Issue by ZinovNikita** [RasmusBV/node-mlt#1]
My code:

    const { MLT } = require('node-mlt');
    const video = new MLT.Producer.Video('D:\\Users\\ZinovNA\\Videos\\results/1695422013358.mp4')
    const playlist = new MLT.Playlist([{
        element: video,
        timestamp: {in: 0, out: 200}
    }])
    const tractor = new MLT.Tractor([{
        element: playlist
    }])
    const filter = new MLT.Filter("dance",{
        frequency_low: 120,
        threshold: -100,
        osc: 80,
        initial_zoom: 100,
        zoom: 10
    })
    tractor.addFilter(filter, playlist)
    
    const consumer = MLT.Consumer.Video("D:\\Users\\ZinovNA\\Videos\\results/1695422013358_res.mp4")
    
    const document = new MLT.Document()
        .addRoot(tractor)
        .addConsumer(consumer)
    MLT.melt(document)

Error:

    D:\Users\ZinovNA\Documents\nodejs\clip-generator\node_modules\node-mlt\lib\cjs\nodes.js:42
                const { element, timestamp = undefined, children: grandChildren = undefined } = children[i];
                        ^
    
    TypeError: Cannot destructure property 'element' of 'children[i]' as it is undefined.
        at new ParentNode (D:\Users\ZinovNA\Documents\nodejs\clip-generator\node_modules\node-mlt\lib\cjs\nodes.js:42:21)
        at new Service (D:\Users\ZinovNA\Documents\nodejs\clip-generator\node_modules\node-mlt\lib\cjs\nodes.js:108:21)
        at new Filter (D:\Users\ZinovNA\Documents\nodejs\clip-generator\node_modules\node-mlt\lib\cjs\nodes\filter.js:7:9)
        at Object.<anonymous> (D:\Users\ZinovNA\Documents\nodejs\clip-generator\test-mlt.js:10:16)
        at Module._compile (node:internal/modules/cjs/loader:1254:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
        at Module.load (node:internal/modules/cjs/loader:1117:32)
        at Module._load (node:internal/modules/cjs/loader:958:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        at node:internal/main/run_main_module:23:47

add console.log to node_modules\node-mlt\lib\cjs\nodes.js:
![image](https://github.com/RasmusBV/node-mlt/assets/18033991/44129a63-a618-4c2c-aa9d-0c40bbdc8e76)
result:
![image](https://github.com/RasmusBV/node-mlt/assets/18033991/e2315ced-4a36-4b7b-a764-ca87f876a0dd)

**Comment by ZinovNikita** [comment]
fix it in my code.
![image](https://github.com/RasmusBV/node-mlt/assets/18033991/7cf08c5a-5d80-4460-b1cb-f82ab89f4b31)
